<?php

    require_once '../App/ValidaLogin.php';
    require_once '../App/Views/adm/menuEvento.phtml';

?>

<section class="grid-base">
    <main class="content">
        <h1 class="title-center-align">Meus Eventos</h1>
        <hr>
        <section class="card">
            <?php foreach($this->view->eventos as $evento) { ?>
                <form action="/acao_evento" method="post" class="card-evento card-block">
                    <div class="card-img card-img-evento">
                        <?php if($evento['imgEvento'] != ''){ ?>
                            <img src="<?= $evento['imgEvento'] ?>" alt="evento">
                        <?php } else { ?>
                            <img src="./img/evento.jpg" alt="evento">
                        <?php } ?>
                    </div>
                    <div class="body-card body-card-evento">
                        <h1><?= $evento['titulo'] ?></h1>
                        <div>Responsável: <strong><?= $evento['nome'] ?></strong></div>
                        <div>Local: <strong><?= $evento['local'] ?></strong></div>
                        <div>Início: <strong><?= $evento['diaInicio'] ?>/<?= $evento['mesInicio'] ?>/<?= $evento['anoInicio'] ?></strong> Fim: <strong><?= $evento['dataFim'] ?></strong></div>
                        <p><?= $evento['descricao'] ?></p>
                        <div class="btn-card btn-card-evento">
                            <button type="submit" value="<?= $evento['id'] ?>" name="cancelar" class="btn-danger-full">Cancelar</button>
                            <button type="submit" value="<?= $evento['id'] ?>" name="alterar" class="btn-warning-full">Alterar</button>
                            <button type="submit" value="<?= $evento['id'] ?>" name="atividades" class="btn-confirm-full">Atividades</button>
                        </div>
                    </div>
                </form>
            <?php } ?>
        </section>
    </main>
</section>