<?php

    require_once '../App/ValidaLogin.php';

?>
<section class="grid-base">
    <aside class="menu-lateral">
        <div class="form-align">
            <h1>Logo SGE</h1>
            <img src="./img/user.png" alt="user" class="img-perfil">
            <h1 class="apelido">Beatriz Santiago</h1>
        </div>
        <nav class="menu">
            <a href="/index_evento">Meus Eventos</a>
            <a onclick="requisitarPagina('/criar_evento')">Criar Evento</a>
            <a onclick="requisitarPagina('/responsavel_geral')">Responsável Geral</a>
            <a href="/sair">Sair</a>
        </nav>
    </aside>
    <main class="content" id="content">
        <h1 class="title-eventos">Meus Eventos</h1>
        <hr>
        <section class="cards-blocks">
            <?php foreach($this->view->eventos as $evento) { ?>
                <form action="/acao_evento" method="post" class="card-evento">
                    <div class="card-img">
                        <?php if($evento['imgEvento'] != ''){ ?>
                            <img src="<?= $evento['imgEvento'] ?>" alt="evento">
                        <?php } else { ?>
                            <img src="./img/evento.jpg" alt="evento">
                        <?php } ?>
                    </div>
                    <div class="body-card">
                        <h1><?= $evento['titulo'] ?></h1>
                        <div>Responsável: <strong><?= $evento['nome'] ?></strong></div>
                        <div>Local: <strong><?= $evento['local'] ?></strong></div>
                        <div>Início: <strong><?= $evento['diaInicio'] ?>/<?= $evento['mesInicio'] ?>/<?= $evento['anoInicio'] ?></strong> Fim: <strong><?= $evento['dataFim'] ?></strong></div>
                        <p><?= $evento['descricao'] ?></p>
                        <div class="btn-card">
                            <button type="submit" value="<?= $evento['id'] ?>" name="cancelar" class="btn-danger-full">Cancelar</button>
                            <button type="submit" value="<?= $evento['id'] ?>" name="alterar" class="btn-warning-full">Alterar</button>
                            <button type="submit" value="<?= $evento['id'] ?>" name="atividades" class="btn-confirm-full">Atividades</button>
                        </div>
                    </div>
                </form>
            <?php } ?>
        </section>
    </main>
</section>