<?php

    require_once '../App/ValidaLoginAdministrador.php';

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <h1 class="apelido">Beatriz Santiago</h1>
        </div>
        <nav class="menu">
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>
    
    <main class="content">

    <div class="form-align">
        <?php foreach($this->view->dadosEventos as $dadosEventos) { ?>
            <form action="/atualizar_evento?dXNlcklE=<?= base64_encode($_SESSION['administradorID']) ?>" method="post" class="form-register space-top">
                <div class="input-grande">
                    <span>Nome</span>
                    <input type="text" value="<?= $dadosEventos['titulo'] ?>" name="titulo" maxlength="50" class="input-radius">
                </div>
                <div class="input-medio">
                    <label>Local</label>
                    <input type="text" value="<?= $dadosEventos['local'] ?>" name="local" maxlength="50" class="input-radius">
                </div>
                <div class="input-medio">
                    <label>Responsável Geral</label>
                    <select class="input-radius" name="responsavelGeral">
                        <option value="">Selecione</option>
                        <?php 
                            foreach($this->view->dadosResponsavel as $dadosResponsavel) { 
                                if($dadosResponsavel['nome'] == $dadosEventos['nome']) {
                        ?>
                            <option value="<?= $dadosResponsavel['id'] ?>" selected><?= $dadosResponsavel['nome'] ?></option>
                        <?php } else { ?>
                            <option value="<?= $dadosResponsavel['id'] ?>"><?= $dadosResponsavel['nome'] ?></option>
                        <?php } } ?>
                    </select>
                </div>
                <div class="input-medio">
                    <label>Data de Início</label>
                    <input type="date" value="<?= $dadosEventos['dataInicio'] ?>" name="dataInicio" class="input-radius">
                </div>
                <div class="input-medio">
                    <label>Data de Término</label>
                    <input type="date" value="<?= $dadosEventos['dataFim'] ?>" name="dataFim" class="input-radius">
                </div>
                <div class="input-medio">
                    <label>Descrição</label>
                    <textarea name="descricao" class="radius-textarea" rows="5" maxlength="140"><?= $dadosEventos['descricao'] ?></textarea>
                </div>
                <!-- <div class="input-medio">
                    <label>Imagem/logo</label>
                    <input type="file" name="imgEvento">
                </div> -->
                <div class="input-grande">
                    <button type="submit" value="<?= $dadosEventos['id'] ?>" name="id" class="btn-register btn-right btn-space-top">Alterar Evento</button>
                    <a href="/index_evento?dXNlcklE=<?= base64_encode($_SESSION['administradorID']) ?>" class="btn-link btn-right btn-space-top btn-confirm">Voltar</a>
                </div>
            </form>
        <?php } ?>
    </div>

    </main>
</section>