<?php

    require_once '../App/ValidaLoginResponsavelGeral.php';

    if($_SESSION['tipoUsuario'] == 'Administrador') {
        $url = '';
    }

    if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') {
        $url = '?dXNlcklE=' . base64_encode($_SESSION['ResponsavelGeralID']);
    }

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <?php if($_SESSION['tipoUsuario'] != 'Administrador' && $this->view->fotoPerfil[0]['imgUser'] != '') { ?>
                <img src="<?= $this->view->fotoPerfil[0]['imgUser'] ?>" alt="user" class="img-perfil">
            <?php } else { ?>
                <img src="./img/user.png" alt="user" class="img-perfil">
            <?php } ?>
            <div class="bemvindo">
                <h3>Bem-vindo(a),</h3>
                <h1 class="apelido"><?= ($_SESSION['apelido'] != '') ? $_SESSION['apelido'] : $_SESSION['login'] ?></h1>
            </div>
        </div>
        <nav class="menu">
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>
    
    <main class="content">

    <div class="form-align">
        <?php foreach($this->view->dadosEventos as $dadosEventos) { ?>
        <form action="/atualizar_evento<?= $url ?>" method="post" class="form-register space-top">

            <?php if($this->view->erroEvento) { ?>
                <div class="msg-box msg-error">
                    <small class="text-error"><strong>Não foi possível alterar este evento!</strong> Modifique corretamente os campos necessários. </small>
                </div>
            <?php } ?>

                <div class="input-grande">
                    <span>Nome</span>
                    <input type="text" value="<?= $dadosEventos['titulo'] ?>" name="titulo" maxlength="50" class="input-radius">
                </div>
                <div class="input-grande">
                    <label>Local</label>
                    <input type="text" value="<?= $dadosEventos['local'] ?>" name="local" maxlength="50" class="input-radius">
                </div>
                <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                    <div class="input-grande">
                        <label>Responsável Geral</label>
                        <select class="input-radius" name="responsavelGeral">
                            <option value="">Selecione</option>
                            <?php 
                                foreach($this->view->dadosResponsavel as $dadosResponsavel) { 
                                    if($dadosResponsavel['nome'] == $dadosEventos['nome']) {
                            ?>
                                <option value="<?= $dadosResponsavel['id'] ?>" selected><?= $dadosResponsavel['nome'] ?></option>
                            <?php } else { ?>
                                <option value="<?= $dadosResponsavel['id'] ?>"><?= $dadosResponsavel['nome'] ?></option>
                            <?php } } ?>
                        </select>
                    </div>
                <?php } ?>
                <div class="input-medio">
                    <label>Data de Início</label>
                    <input type="date" value="<?= $dadosEventos['dataInicio'] ?>" name="dataInicio" class="input-radius">
                </div>
                <div class="input-medio">
                    <label>Data de Término</label>
                    <input type="date" value="<?= $dadosEventos['dataFim'] ?>" name="dataFim" class="input-radius">
                </div>
                <div class="input-grande">
                    <label>Descrição</label>
                    <textarea name="descricao" class="radius-textarea" rows="5" maxlength="140"><?= $dadosEventos['descricao'] ?></textarea>
                </div>
                <!-- <div class="input-medio">
                    <label>Imagem/logo</label>
                    <input type="file" name="imgEvento">
                </div> -->
                <div class="input-grande">
                    <button type="submit" value="<?= $dadosEventos['id'] ?>" name="id" class="btn-register btn-right btn-space-top">Alterar Evento</button>
                    <a href="/index_evento<?= $url ?>" class="btn-link btn-right btn-space-top btn-confirm">Voltar</a>
                </div>
            </form>
        <?php } ?>
    </div>

    </main>
</section>