<?php

    require_once '../App/ValidaLogin.php';
    foreach($this->view->dadosEventos as $dadosEventos) {
        echo "<pre>";
        print_r($dadosEventos);
        echo "</pre>";
    }

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <h1 class="apelido">Beatriz Santiago</h1>
        </div>
        <nav class="menu">
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>
    
    <main class="content">

    <div class="form-align">
        <?php foreach($this->view->dadosEventos as $dadosEventos) { ?>
            <form action="/atualizar_evento" method="post" class="form-register space-top">
                <div class="input-grande">
                    <span>Nome</span>
                    <input type="text" value="<?= $dadosEventos['titulo'] ?>" name="titulo" maxlength="50" class="input-radius">
                </div>
                <div class="input-medio">
                    <label>Local</label>
                    <input type="text" value="<?= $dadosEventos['local'] ?>" name="local" maxlength="50" class="input-radius">
                </div>
                <div class="input-medio">
                    <label>Responsável Geral</label>
                    <select class="input-radius" name="responsavelGeral">
                        <option value="">Selecione</option>
                    </select>
                </div>
                <div class="input-medio">
                    <div class="input-pequeno">
                        <label>Dia</label>
                        <input type="text" value="<?= $dadosEventos['diaInicio'] ?>" name="diaInicio" class="input-radius">
                    </div>
                    <div class="input-pequeno">
                        <label>Mês</label>
                        <input type="text" value="<?= $dadosEventos['mesInicio'] ?>" name="mesInicio" class="input-radius">
                    </div>
                    <div class="input-pequeno">
                        <label>Ano</label>
                        <input type="text" value="<?= $dadosEventos['anoInicio'] ?>" name="anoInicio" class="input-radius">
                    </div>
                </div>
                <div class="input-medio">
                    <label>Data de Término</label>
                    <input type="date" value="<?= $dadosEventos['dataFim'] ?>" name="dataFim" class="input-radius">
                </div>
                <div class="input-medio">
                    <label>Descrição</label>
                    <textarea name="descricao" class="radius-textarea" rows="5" maxlength="140"><?= $dadosEventos['descricao'] ?></textarea>
                </div>
                <!-- <div class="input-medio">
                    <label>Imagem/logo</label>
                    <input type="file" name="imgEvento">
                </div> -->
                <div class="input-grande">
                    <button type="submit" value="<?= $dadosEventos['id'] ?>" name="id" class="btn-register btn-right btn-space-top">Alterar Evento</button>
                    <a href="/index_evento" class="btn-link btn-right btn-space-top btn-confirm">Voltar</a>
                </div>
            </form>
        <?php } ?>
    </div>

    </main>
</section>