<?php

    require_once '../App/ValidaLoginResponsavelGeral.php';

    if($_SESSION['tipoUsuario'] == 'Administrador') {
        $url = '';
    }

    if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') {
        $url = '?dXNlcklE=' . base64_encode($_SESSION['ResponsavelGeralID']);
    }

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <?php if($_SESSION['tipoUsuario'] != 'Administrador' && $this->view->fotoPerfil[0]['imgUser'] != '') { ?>
                <img src="<?= $this->view->fotoPerfil[0]['imgUser'] ?>" alt="user" class="img-perfil">
            <?php } else { ?>
                <img src="./img/user.png" alt="user" class="img-perfil">
            <?php } ?>
            <div class="bemvindo">
                <h3>Bem-vindo(a),</h3>
                <h1 class="apelido"><?= ($_SESSION['apelido'] != '') ? $_SESSION['apelido'] : $_SESSION['login'] ?></h1>
            </div>
        </div>
        <nav class="menu">
            <a href="/index_evento<?= $url ?>"><img src="./img/icons/eventos.png">Eventos</a>

            <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                <a href="/responsavel_geral"><img src="./img/icons/resp-geral.png">Responsável Geral</a>
            <?php } ?>

            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>
    
    <main class="content">

    <div class="form-align">
        <form enctype="multipart/form-data" action="/cadastrar_evento<?= $url ?>" method="post" class="form-register space-top">
            <?php if($this->view->erroEvento) { ?>
                <div class="msg-box msg-error">
                    <small class="text-error"><strong>Erro ao tentar criar o evento!</strong> Verifique se os campos foram preenchidos corretamente. </small>
                </div>
            <?php } ?>

            <div class="input-grande">
                <span>Nome</span>
                <input type="text" name="titulo" maxlength="50" class="input-radius" value="<?= $this->view->evento['titulo'] ?>" autofocus>
                <?php if(isset($this->view->erroTitulo) && $this->view->erroTitulo != false) { ?>
                    <small class="text-error"><strong>Informe um nome válido!</strong></small>
                <?php } ?>
            </div>
            <div class="input-grande">
                <label>Local</label>
                <input type="text" name="local" maxlength="50" class="input-radius" value="<?= $this->view->evento['local'] ?>">
                <?php if(isset($this->view->erroLocal) && $this->view->erroLocal != false) { ?>
                    <small class="text-error"><strong>Informe um local válido!</strong></small>
                <?php } ?>
            </div>

            <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                <div class="input-grande">
                    <label>Responsável Geral</label>

                    <select class="input-radius" name="responsavelGeral">
                        <option value="">Selecione</option>
                        
                        <?php foreach($this->view->responsavel_geral as $responsavel_geral) {
                            if($this->view->evento['responsavelGeral'] == $responsavel_geral['id']) { ?>
                                <option value="<?= $responsavel_geral['id'] ?>" selected><?= $responsavel_geral['nome'] ?></option>
                            <?php } else { ?>
                                <option value="<?= $responsavel_geral['id'] ?>"><?= $responsavel_geral['nome'] ?></option>
                        <?php } } ?>
                    </select>

                    <?php if(isset($this->view->erroResponsavelGeral) && $this->view->erroResponsavelGeral != false) { ?>
                        <small class="text-error"><strong>Informe um Responsável Geral!</strong></small>
                    <?php } ?>
                </div>
            <?php } ?>
            
            <div class="input-medio">
                <label>Data de Início</label>
                <input type="date" name="dataInicio" class="input-radius" value="<?= $this->view->evento['dataInicio'] ?>">
                <?php if(isset($this->view->erroDataInicio) && $this->view->erroDataInicio != false) { ?>
                    <small class="text-error"><strong>Informe uma data inicial válida!</strong></small>
                <?php } ?>
            </div>
            <div class="input-medio">
                <label>Data de Término</label>
                <input type="date" name="dataFim" class="input-radius" value="<?= $this->view->evento['dataFim'] ?>">
                <?php if(isset($this->view->erroDataFim) && $this->view->erroDataFim != false) { ?>
                    <small class="text-error"><strong>Informe uma data final válida!</strong></small>
                <?php } ?>
            </div>
            <div class="input-medio">
                <label>Descrição</label>
                <textarea name="descricao" class="radius-textarea" rows="5" maxlength="140" value="<?= $this->view->evento['descricao'] ?>"></textarea>
            </div>
            <div class="input-medio">
                <input type="hidden" name="MAX_FILE_SIZE" value="15728640" />
                <label>Imagem/logo</label>
                <input type="file" name="imgEvento" accept="image/*">
                <?php if(isset($this->view->erroImage) && $this->view->erroImage != false) { ?>
                    <small class="text-error"><strong>A imagem excede o limite de tamanho!</strong></small>
                <?php } ?>
            </div>
            <div class="input-grande">
                <button type="submit" class="btn-register btn-right btn-space-top">Adicionar Evento</button>
                <a href="/index_evento<?= $url ?>" class="btn-link btn-right btn-space-top btn-confirm">Voltar</a>
            </div>
        </form>
    </div>

    </main>
</section>