<?php

    require_once '../App/ValidaLoginResponsavelGeral.php';

    if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') {
        $ResponsavelGeral = base64_encode($_SESSION['ResponsavelGeralID']);
    }

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <h1 class="apelido">Beatriz Santiago</h1>
        </div>
        <nav class="menu">
            <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                <a href="/index_evento"><img src="./img/icons/eventos.png">Eventos</a>
                <a href="/responsavel_geral"><img src="./img/icons/resp-geral.png">Responsável Geral</a>
            <?php } ?>

            <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                <a href="/index_evento?dXNlcklE=<?= $ResponsavelGeral ?>"><img src="./img/icons/eventos.png">Eventos</a>
            <?php } ?>

            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>
    
    <main class="content">

    <div class="form-align">
        <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
            <form action="/cadastrar_evento" method="post" class="form-register space-top">
        <?php } ?>

        <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
            <form action="/cadastrar_evento?dXNlcklE=<?= $ResponsavelGeral ?>" method="post" class="form-register space-top">
        <?php } ?>
            <div class="input-grande">
                <span>Nome</span>
                <input type="text" name="titulo" maxlength="50" class="input-radius">
            </div>
            <div class="input-grande">
                <label>Local</label>
                <input type="text" name="local" maxlength="50" class="input-radius">
            </div>
            <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                <div class="input-grande">
                    <label>Responsável Geral</label>
                    <select class="input-radius" name="responsavelGeral">
                        <option value="">Selecione</option>
                        <?php foreach($this->view->responsavel_geral as $responsavel_geral) { ?>
                            <option value="<?= $responsavel_geral['id'] ?>"><?= $responsavel_geral['nome'] ?></option>
                        <?php } ?>
                    </select>
                </div>
            <?php } ?>
            <div class="input-medio">
                <label>Data de Início</label>
                <input type="date" name="dataInicio" class="input-radius">
            </div>
            <div class="input-medio">
                <label>Data de Término</label>
                <input type="date" name="dataFim" class="input-radius">
            </div>
            <div class="input-medio">
                <label>Descrição</label>
                <textarea name="descricao" class="radius-textarea" rows="5" maxlength="140"></textarea>
            </div>
            <div class="input-medio">
                <label>Imagem/logo</label>
                <input type="file" name="imgEvento">
            </div>
            <div class="input-grande">
                <button type="submit" class="btn-register btn-right btn-space-top">Adicionar Evento</button>

                <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                    <a href="/index_evento" class="btn-link btn-right btn-space-top btn-confirm">Voltar</a>
                <?php } ?>
                
                <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                    <a href="/index_evento?dXNlcklE=<?= $ResponsavelGeral ?>" class="btn-link btn-right btn-space-top btn-confirm">Voltar</a>
                <?php } ?>
            </div>
        </form>
    </div>

    </main>
</section>