<?php

    require_once '../App/ValidaLogin.php';

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <h1 class="apelido">Beatriz Santiago</h1>
        </div>
        <nav class="menu">
            <a href="/index_evento"><img src="./img/icons/eventos.png">Meus Eventos</a>
            <a href="/responsavel_geral"><img src="./img/icons/resp-geral.png">Responsável Geral</a>
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>
    
    <main class="content">

    <div class="form-align">
        <form action="/cadastrar_evento" method="post" class="form-register space-top">
            <div class="input-grande">
                <span>Nome</span>
                <input type="text" name="titulo" maxlength="50" class="input-radius">
            </div>
            <div class="input-medio">
                <label>Local</label>
                <input type="text" name="local" maxlength="50" class="input-radius">
            </div>
            <div class="input-medio">
                <label>Responsável Geral</label>
                <select class="input-radius" name="responsavelGeral">
                    <option value="">Selecione</option>
                    <?php foreach($this->view->responsavel_geral as $responsavel_geral) { ?>
                        <option value="<?= $responsavel_geral['id'] ?>"><?= $responsavel_geral['nome'] ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="input-medio">
                <label>Data de Início</label>
                <input type="date" name="dataInicio" class="input-radius">
            </div>
            <div class="input-medio">
                <label>Data de Término</label>
                <input type="date" name="dataFim" class="input-radius">
            </div>
            <div class="input-medio">
                <label>Descrição</label>
                <textarea name="descricao" class="radius-textarea" rows="5" maxlength="140"></textarea>
            </div>
            <div class="input-medio">
                <label>Imagem/logo</label>
                <input type="file" name="imgEvento">
            </div>
            <div class="input-grande">
                <button type="submit" class="btn-register btn-right btn-space-top">Adicionar Evento</button>
            </div>
        </form>
    </div>

    </main>
</section>