<?php

    require_once '../App/ValidaLoginResponsavelGeral.php';

    if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') {
        $ResponsavelGeral = base64_encode($_SESSION['ResponsavelGeralID']);
    }

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <h1 class="apelido">Beatriz Santiago</h1>
        </div>
        <nav class="menu">
            <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                <a href="/index_evento"><img src="./img/icons/eventos.png">Eventos</a>
                <a href="/criar_evento"><img src="./img/icons/criar-evento.png">Criar Evento</a>
                <a href="/responsavel_geral"><img src="./img/icons/resp-geral.png">Responsável Geral</a>
            <?php } ?>

            <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                <a href="/index_evento?dXNlcklE=<?= $ResponsavelGeral ?>"><img src="./img/icons/eventos.png">Eventos</a>
                <a href="/criar_evento?dXNlcklE=<?= $ResponsavelGeral ?>"><img src="./img/icons/criar-evento.png">Criar Evento</a>
            <?php } ?>

            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">
        <h1 class="title-center-align">Eventos</h1>
        <hr>
        <section class="card">
            <?php foreach($this->view->eventos as $evento) { ?>
                <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                    <form action="/acao_evento" method="post" class="card-evento card-block">
                <?php } ?>
                <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                    <form action="/acao_evento?dXNlcklE=<?= $ResponsavelGeral ?>" method="post" class="card-evento card-block">
                <?php } ?>
                    <div class="card-img card-img-evento">
                        <?php if($evento['imgEvento'] != ''){ ?>
                            <img src="<?= $evento['imgEvento'] ?>" alt="evento">
                        <?php } else { ?>
                            <img src="./img/evento.png" alt="evento">
                        <?php } ?>
                    </div>
                    <div class="body-card body-card-evento">
                        <h1><?= $evento['titulo'] ?></h1>
                        <div>Responsável: <strong><?= $evento['nome'] ?></strong></div>
                        <div>Local: <strong><?= $evento['local'] ?></strong></div>
                        <div>Início: <strong><?= $evento['dataInicio'] ?></strong> Fim: <strong><?= $evento['dataFim'] ?></strong></div>
                        <p><?= $evento['descricao'] ?></p>
                        <div class="btn-card btn-card-evento">
                            <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                                <button type="submit" value="<?= $evento['id'] ?>" name="excluir" class="btn-evil-full">Excluir</button>
                            <?php } ?>

                            <?php if($evento['cancelado'] == false) { ?>
                                <button type="submit" value="<?= $evento['id'] ?>" name="cancelar" class="btn-danger-full">Cancelar</button>
                            <?php } else { ?>
                                <button type="submit" value="<?= $evento['id'] ?>" name="ativar" class="btn-register-full">Ativar</button>
                            <?php } ?>
                            
                            <button type="submit" value="<?= $evento['id'] ?>" name="alterar" class="btn-warning-full">Alterar</button>
                        </div>
                        <div class="btn-card">
                            <button type="submit" value="<?= $evento['id'] ?>" name="atividades" class="btn-confirm-full btn-block">Atividades</button>
                        </div>
                    </div>
                </form>
            <?php } ?>
        </section>
    </main>
</section>