<aside class="menu-lateral">
    <div class="form-align">
        <h1>Logo SGE</h1>
        <img src="./img/user.png" alt="user" class="img-perfil">
        <h1 class="apelido">Beatriz Santiago</h1>
    </div>
    <nav class="menu">
        <a href="/index_evento"><img src="./img/icons/eventos.png">Meus Eventos</a>
        <a href="/criar_evento"><img src="./img/icons/criar-evento.png">Criar Evento</a>
        <a href="/responsavel_geral"><img src="./img/icons/resp-geral.png">Responsável Geral</a>
        <a href="/sair" class="sair">Sair</a>
    </nav>
</aside>