<?php

    require_once '../App/ValidaLoginAdministrador.php';

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <div class="bemvindo">
                <h3>Bem-vindo(a),</h3>
                <h1 class="apelido"><?= ($_SESSION['apelido'] != '') ? $_SESSION['apelido'] : $_SESSION['login'] ?></h1>
            </div>
        </div>
        <nav class="menu">
            <a href="/index_evento"><img src="./img/icons/eventos.png">Eventos</a>
            <a href="/criar_evento"><img src="./img/icons/criar-evento.png">Criar Evento</a>
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">

    <section class="form-align">
        <form action="/cadastrar_responsavel_geral" method="post" class="form-register">
            <h1 class="title-center-align">Cadastrar Responsável Geral</h1>
            <div class="input-grande">
                <label>E-mail do Usuário</label>
                <input type="email" name="login" class="input-radius" value="<?= $this->view->responsavelGeral['login'] ?>">
                <?php if(isset($this->view->erroEmailCadastrado) && $this->view->erroEmailCadastrado != false) { ?>
                    <small class="text-error"><strong> Este Responsável Geral já existe!</strong></small>
                <?php } ?>
                <?php if(isset($this->view->erroEmail) && $this->view->erroEmail != false) { ?>
                    <small class="text-error"><strong> Informe um e-mail!</strong></small>
                <?php } ?>
            </div>
            <div class="input-grande btn-align-center btn-space-top">
                <button type="submit" class="btn-register">Adicionar Responsável</button>
            </div>
        </form>
    </section>

    <h1 class="title-center">Responsável Geral</h1>
    <hr style="width: 70%;">

    <section class="lista-container">
        <div class="lista">
            <?php foreach($this->view->responsavel_geral as $item) {?>
                <form action="/remover_responsavel_geral" method="post" class="item-lista">
                    <div class="item-medio"><?= $item['nome'] ?></div>
                    <div class="item-pequeno"><?= $item['login'] ?></div>
                    <div class="item-button">
                        <button type="submit" value="<?= $item['id'] ?>" name="remover" class="btn-danger-full"><img class="img-button" src="./img/icons/cancel.png" /></button>
                    </div>
                </form>
            <?php } ?>
        </div>
    </section>

    </main>
</section>