<?php

    require_once '../App/ValidaLoginParticipante.php';

    $eventoID = $_GET['idEvt'];

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <h1 class="apelido">Beatriz Santiago</h1>
        </div>
        <nav class="menu">
            <a href="/index_participante"><img src="./img/icons/eventos.png">Eventos</a>
            <a href="#"><img src="./img/icons/criar-evento.png">Cronograma</a>
            
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">
        <h1 class="title-center-align">Atividades de <?= $this->view->titulo[0]['titulo'] ?></h1>
        <hr>
        <section class="card">
            <?php foreach($this->view->atividades as $atividade) { ?>
                <? if($atividade['cancelada'] == 0) { ?>
                <form action="/acao_participante_atividade?cGFydGljaXBhbnRl=<?= base64_encode($_SESSION['id']) ?>&idEvt=<?= $eventoID ?>" method="post" class="card-atividade card-block">
                    <div class="body-card body-card-atividade">
                        <h1><?= $atividade['tipo'] ?></h1>
                        <div class="div-grande">Tema: <strong><?= $atividade['tema'] ?></strong></div>
                        <div class="div-grande">Palestrante <strong><?= $atividade['palestrante'] ?></strong></div>
                        <div class="div-grande">Responsável: <strong><?= $atividade['nome'] ?></strong></div>
                        <div class="div-grande">Local: <strong><?= $atividade['local'] ?></strong></div>

                        <div class="div-grande">
                            <div class="div-media">Data: <strong><?= $atividade['data'] ?></strong></div>
                            <div class="div-media">Hora: <strong><?= $atividade['hora'] ?>h</strong></div>
                        </div>
                        
                        <div class="div-grande">
                            <div class="div-media">Duração: <strong><?= $atividade['duracao'] ?>h</strong></div>
                            <div class="div-media">Pontos Pex: <strong><?= $atividade['pontosPex'] ?></strong></div>
                        </div>
                        <div class="div-grande">
                            <div class="div-media">Total de Vagas: <strong><?= $atividade['vagasMaximas'] ?></strong></div>
                            <div class="div-media">Vagas Restantes: <strong> -- </strong></div>
                        </div>

                        <?php if($atividade['descricao'] != '') { ?>
                            <p><?= $atividade['descricao'] ?></p>
                        <?php } else { ?>
                            <br/>
                        <?php } ?>

                        <div class="btn-card btn-card-atividade-p">
                            <button type="submit" name="cancelarInscricaoAtividade" value="<?= $atividade['id'] ?>" class="btn-danger-full">Cancelar Inscrição</button>
                            <button type="submit" name="inscreverAtividade" value="<?= $atividade['id'] ?>" class="btn-register-full">Inscrever - me</button>
                        </div>
                    </div>
                </form>
                <?php } ?>
            <?php } ?>
        </section>
    </main>
</section>