<?php

    require_once '../App/ValidaLoginParticipante.php';

    $eventoID = $_GET['idEvt'];
    $usuarioID = $_GET['cGFydGljaXBhbnRl'];

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <h1 class="apelido">Beatriz Santiago</h1>
        </div>
        <nav class="menu">
            <a href="/index_participante?cGFydGljaXBhbnRl=<?= $usuarioID ?>"><img src="./img/icons/eventos.png">Eventos</a>
            <a href="/gerar_certificado?cGFydGljaXBhbnRl=<?= $usuarioID ?>&idEvt=<?= $eventoID ?>"><img src="./img/icons/relatorio.png">Certificados</a>
            <a href="#"><img src="./img/icons/criar-evento.png">Cronograma</a>
            
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">
        <h1 class="title-center-align">Atividades de <?= $this->view->titulo[0]['titulo'] ?></h1>
        <hr>
        <?php if($this->view->atividades == []) { ?>
            <div class="mensagem-aviso">
                <div class="msg-box-medium msg-info">
                    <small class="text-info">Ainda <strong>não existem atividades</strong> para este evento!</small>
                </div>
            </div>
        <?php } ?>
        <section class="card">
            <?php foreach($this->view->atividades as $atividade) { ?>
                <? if($atividade['cancelada'] == 0) { ?>
                <form action="/acao_participante_atividade?cGFydGljaXBhbnRl=<?= $usuarioID ?>&idEvt=<?= $eventoID ?>" method="post" class="card-atividade card-block" style="border: solid 1px <?= $atividade['cor'] ?>">
                    <div class="body-card body-card-atividade">
                        <h1 style="color: <?= $atividade['cor'] ?>"><?= $atividade['tipo'] ?></h1>
                        <div class="div-grande">Tema: <strong><?= $atividade['tema'] ?></strong></div>

                        <div class="div-grande dados-palestrante" style="border-bottom-color: <?= $atividade['cor'] ?>">
                            <div class="div-palestrante">Palestrante: <strong><?= $atividade['palestrante'] ?></strong></div>
                            <?php if($atividade['imgPalestrante'] != ''){ ?>
                                <div class="div-pequena align-img"><img class="img-palestrante" src="<?= $atividade['imgPalestrante'] ?>" alt="palestrante"></div>
                            <?php } else { ?>
                                <div class="div-pequena align-img"><img class="img-palestrante" src="./img/icons/palestrante.jpg" alt="palestrante"></div>
                            <?php } ?>
                        </div>

                        <div class="div-grande">Responsável: <strong><?= $atividade['nome'] ?></strong></div>
                        <div class="div-grande">Local: <strong><?= $atividade['local'] ?></strong></div>

                        <div class="div-grande">
                            <div class="div-media">Data: <strong><?= $atividade['data'] ?></strong></div>
                            <div class="div-media">Hora: <strong><?= $atividade['hora'] ?>h</strong></div>
                        </div>
                        
                        <div class="div-grande">
                            <div class="div-media">Duração: <strong><?= $atividade['duracao'] ?>h</strong></div>
                            <div class="div-media">Pontos Pex: <strong><?= $atividade['pontosPex'] ?></strong></div>
                        </div>
                        <div class="div-grande">Vagas Restantes: <strong><?= $atividade['vagasMaximas'] - $atividade['qtdInscritos'] ?></strong></div>

                        <?php if($atividade['descricao'] != '') { ?>
                            <p><?= $atividade['descricao'] ?></p>
                        <?php } else { ?>
                            <br/>
                        <?php } ?>

                        <div class="btn-card btn-card-atividade-p">
                            <?php if($atividade['usuarioID'] == $_SESSION['id']) { ?>
                                <button type="submit" name="cancelarInscricaoAtividade" value="<?= $atividade['id'] ?>" class="btn-danger-full">Cancelar Inscrição</button>
                            <?php } else { ?>
                                <button type="submit" name="inscreverAtividade" value="<?= $atividade['id'] ?>" class="btn-register-full">Inscrever - me</button>
                            <?php } ?>
                        </div>
                    </div>
                </form>
                <?php } ?>
            <?php } ?>
        </section>
    </main>
</section>