<?php

    require_once '../App/ValidaLoginParticipante.php';

    $eventoID = $_GET['idEvt'];

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <h1 class="apelido">Beatriz Santiago</h1>
        </div>
        <nav class="menu">
            <a href="/index_participante"><img src="./img/icons/eventos.png">Eventos</a>

            <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                <a href="/criar_atividade?idEvt=<?= $eventoID ?>"><img src="./img/icons/criar-atv.png">Criar Atividade</a>
                <a href="/responsavel_atividade?idEvt=<?= $eventoID ?>"><img src="./img/icons/resp-atv.png">Responsável por Atividade</a>
                <a><img src="./img/icons/relatorio.png">Gerar Relatório</a>
            <?php } ?>

            <a href="#"><img src="./img/icons/criar-evento.png">Cronograma</a>
            
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">
        <h1 class="title-center-align">Atividades de Evento</h1>
        <hr>
        <section class="card">
            <?php foreach($this->view->atividades as $atividade) { ?>
                <form action="/acao_participante_atividade?user=<?= base64_encode($_SESSION['id']) ?>&&idEvt=<?= $eventoID ?>" method="post" class="card-atividade card-block">

                    <div class="card-img card-img-atividade">
                        <img src="./img/<?= explode(" ", $atividade['tipo'])[0] ?>.png" alt="Tipo Atividade">
                    </div>

                    <div class="body-card body-card-atividade">
                        <h1><?= $atividade['tipo'] ?></h1>
                        <div class="div-grande">Tema: <strong><?= $atividade['tema'] ?></strong></div>
                        <div class="div-grande">Palestrante <strong><?= $atividade['palestrante'] ?></strong></div>
                        <div class="div-grande">Responsável: <strong><?= $atividade['nome'] ?></strong></div>
                        <div class="div-grande">Local: <strong><?= $atividade['local'] ?></strong></div>

                        <div class="div-grande">
                            <div class="div-pequena">Data: <strong><?= $atividade['data'] ?></strong></div>
                            <div class="div-pequena">Hora: <strong><?= $atividade['hora'] ?>h</strong></div>
                            <div class="div-pequena">Duração: <strong><?= $atividade['duracao'] ?>h</strong></div>
                        </div>

                        <div class="div-grande">
                            <div class="div-pequena">Total de Vagas: <strong><?= $atividade['vagasMaximas'] ?></strong></div>
                            <div class="div-pequena">Vagas Restantes: <strong> -- </strong></div>
                            <div class="div-pequena">Pontos Pex: <strong><?= $atividade['pontosPex'] ?></strong></div>
                        </div>

                        <?php if($atividade['descricao'] != '') { ?>
                            <p><?= $atividade['descricao'] ?></p>
                        <?php } else { ?>
                            <br/>
                        <?php } ?>

                        <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                            <div class="btn-card btn-card-atividade">
                                <button type="submit" name="cancelar" value="<?= $atividade['id'] ?>" class="btn-danger-full">Cancelar</button>
                                <button type="submit" name="alterar" value="<?= $atividade['id'] ?>" class="btn-warning-full">Alterar</button>
                                <button type="submit" name="participantes" value="<?= $atividade['id'] ?>" class="btn-confirm-full">Participantes</button>
                                <button type="submit" name="definirOrganizacao" value="<?= $atividade['id'] ?>" class="btn-register-full">Definir Organização</button>
                            </div>
                        <?php } ?>
                        <?php if($_SESSION['tipoUsuario'] == 'Participante') { ?>
                            <div class="btn-card btn-card-atividade-p">
                                <button type="submit" name="cancelarInscricaoAtividade" value="<?= $atividade['id'] ?>" class="btn-danger-full">Cancelar Inscrição</button>
                                <button type="submit" name="inscreverAtividade" value="<?= $atividade['id'] ?>" class="btn-register-full">Inscrever - me</button>
                            </div>
                        <?php } ?>
                    </div>

                </form>
            <?php } ?>
        </section>
    </main>
</section>