<?php

    require_once '../App/ValidaLoginParticipante.php';
    
    $eventoID = $_GET['idEvt'];
    $usuarioID = $_GET['cGFydGljaXBhbnRl'];

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <div class="bemvindo">
                <h3>Bem-vindo(a),</h3>
                <h1 class="apelido"><?= ($_SESSION['apelido'] != '') ? $_SESSION['apelido'] : $_SESSION['login'] ?></h1>
            </div>
        </div>
        <nav class="menu">
            <a href="/atividades_evento?cGFydGljaXBhbnRl=<?= $usuarioID ?>&idEvt=<?= $eventoID ?>"><img src="./img/icons/atividade.png">Atividades</a>
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">
        <h1 class="title-center-align">Relatório de Participação</h1>
        <br>
        <section class="section-table">
        <?php if($this->view->relatorio == []) { ?>
            <div class="mensagem-aviso">
                <div class="msg-box-medium msg-info">
                    <small class="text-info">Nenhuma <strong>inscrição</strong> foi realizada!</small>
                </div>
            </div>
        <?php } else { ?>
            <table class="table" cellspacing="0px">
                <thead class="table-head">
                    <th class="medium-field">Atividade</th>
                    <th class="small-field">Pontos PEX</th>
                    <th class="small-field">Compareceu?</th>
                    <th class="small-field">Certificado</th>
                </thead>
                <tbody class="table-body">
                    <?php foreach($this->view->relatorio as $item) { ?>
                        <tr>
                            <td class="medium-field"><?= $item['tema'] ?></td>
                            <td class="small-field"><?= $item['pontosPex'] ?></td>
                            <td class="small-field"><?php if($item['presente'] == 0) { echo "Não"; } else { echo "Sim"; } ?></td>
                            <td class="small-field">
                                <?php if($item['presente'] != 0) { ?>
                                    <a href="/imprimir_certificado?idEvt=<?= $_GET['idEvt'] ?>&idAtv=<?= base64_encode($item['id']) ?>&ui=<?= base64_encode($_SESSION['id']) ?>" class="btn-link btn-register" target="_blank">Gerar</a>
                                <?php } ?>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
                <tfoot class="table-foot">
                    <tr>
                        <td class="big-field">Total de Pontos PEX</td>
                        <?php foreach($this->view->somatorio as $somatorio) { ?>
                            <td class="small-field"><?= $somatorio['soma'] ?></td>
                        <?php } ?>
                        <td colspan="2" class="small-field"></td>
                    </tr>
                </tfoot>
            </table>
            <div class="relatorio-buttons">
                <a href="/imprimir_relatorio?idEvt=<?= $_GET['idEvt'] ?>&ui=<?= base64_encode($_SESSION['id']) ?>" class="btn-link btn-confirm" target="_blank">Gerar Relatório</a>
            </div>
        <?php } ?>
        </section>
    </main>
</section>