<?php

    require_once '../App/ValidaLoginParticipante.php';

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <h1 class="apelido">Beatriz Santiago</h1>
        </div>
        <nav class="menu">
            <a href="/index_participante"><img src="./img/icons/eventos.png">Eventos</a>

            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">
        <h1 class="title-center-align">Gerenciar Atividades</h1>
        <hr>
        <section class="card">
            <?php foreach($this->view->atividades as $atividade) { ?>
                <form action="/listar_participante?dXNlcklEQXR2=<?= $_GET['dXNlcklEQXR2'] ?>&idEvt=<?= base64_encode($atividade['eventoID']) ?>&idAtv=<?= base64_encode($atividade['id']) ?>" method="post" class="card-atividade card-block">

                    <div class="card-img card-img-atividade">
                        <img src="./img/<?= explode(" ", $atividade['tipo'])[0] ?>.png" alt="Tipo Atividade">
                    </div>

                    <div class="body-card body-card-atividade">
                        <h1><?= $atividade['tipo'] ?></h1>
                        <div class="div-grande">Tema: <strong><?= $atividade['tema'] ?></strong></div>
                        <div class="div-grande">Palestrante <strong><?= $atividade['palestrante'] ?></strong></div>
                        <div class="div-grande">Responsável: <strong><?= $atividade['nome'] ?></strong></div>
                        <div class="div-grande">Local: <strong><?= $atividade['local'] ?></strong></div>
                        
                        <div class="div-grande">
                            <div class="div-pequena">Data: <strong><?= $atividade['data'] ?></strong></div>
                            <div class="div-pequena">Hora: <strong><?= $atividade['hora'] ?>h</strong></div>
                            <div class="div-pequena">Duração: <strong><?= $atividade['duracao'] ?>h</strong></div>
                        </div>
                        
                        <div class="div-grande">
                            <div class="div-pequena">Total de Vagas: <strong><?= $atividade['vagasMaximas'] ?></strong></div>
                            <div class="div-pequena">Vagas Restantes: <strong> -- </strong></div>
                            <div class="div-pequena">Pontos Pex: <strong><?= $atividade['pontosPex'] ?></strong></div>
                        </div>
                        
                        <div class="div-grande">Evento: <strong><?= $atividade['titulo'] ?></strong></div>

                        <?php if($atividade['descricao'] != '') { ?>
                            <p><?= $atividade['descricao'] ?></p>
                        <?php } else { ?>
                            <br/>
                        <?php } ?>

                        <div class="btn-card btn-card-atividade-p">
                            <button type="submit" class="btn-confirm-full">Gerenciar</button>
                        </div>
                    </div>
                </form>
            <?php } ?>
        </section>
    </main>
</section>