<?php

    require_once '../App/ValidaLoginParticipante.php';

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <h1 class="apelido">Beatriz Santiago</h1>
        </div>
        <nav class="menu">
            <a href="/index_evento"><img src="./img/icons/eventos.png">Eventos</a>
            <a href="#"><img src="./img/icons/criar-evento.png">Cronograma</a>
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">
        <h1 class="title-center-align">Eventos</h1>
        <hr>
        <section class="card">
            <?php foreach($this->view->eventos as $evento) { ?>
                <form action="#" method="post" class="card-evento card-block">
                    <div class="card-img card-img-evento">
                        <?php if($evento['imgEvento'] != ''){ ?>
                            <img src="<?= $evento['imgEvento'] ?>" alt="evento">
                        <?php } else { ?>
                            <img src="./img/evento.png" alt="evento">
                        <?php } ?>
                    </div>
                    <div class="body-card body-card-evento">
                        <h1><?= $evento['titulo'] ?></h1>
                        <div>Responsável: <strong><?= $evento['nome'] ?></strong></div>
                        <div>Local: <strong><?= $evento['local'] ?></strong></div>
                        <div>Início: <strong><?= $evento['dataInicio'] ?></strong> Fim: <strong><?= $evento['dataFim'] ?></strong></div>
                        <p><?= $evento['descricao'] ?></p>
                        <div class="btn-card">
                            <button type="submit" value="<?= $evento['id'] ?>" name="inscreverEvento" class="btn-register-full btn-block">Inscrever - me</button>
                        </div>
                        <div class="btn-card btn-card-evento-p">
                            <button type="submit" value="<?= $evento['id'] ?>" name="sairEvento" class="btn-danger-full">Sair</button>
                            <button type="submit" value="<?= $evento['id'] ?>" name="visualizarAtividades" class="btn-confirm-full">Visualizar Atividades</button>
                        </div>
                    </div>
                </form>
            <?php } ?>
        </section>
    </main>
</section>