<?php

    require_once '../App/ValidaLoginParticipante.php';
    $usuarioID = $_GET['cGFydGljaXBhbnRl'];

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <?php if($this->view->fotoPerfil[0]['imgUser'] != '') { ?>
                <img src="<?= $this->view->fotoPerfil[0]['imgUser'] ?>" alt="user" class="img-perfil">
            <?php } else { ?>
                <img src="./img/user.png" alt="user" class="img-perfil">
            <?php } ?>
            <div class="bemvindo">
                <h3>Bem-vindo(a),</h3>
                <h1 class="apelido"><?= ($_SESSION['apelido'] != '') ? $_SESSION['apelido'] : $_SESSION['login'] ?></h1>
            </div>
        </div>
        <nav class="menu">
            <?php if($_SESSION['tipoUsuario'] == 'ResponsavelAtividade') { ?>
                <a href="/gerenciar_atividades?dXNlcklEQXR2=<?= base64_encode($_SESSION['ResponsavelAtividadeID']) ?>"><img src="./img/icons/criar-atv.png">Gerenciar Atividades</a>
            <?php } ?>
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">
        <h1 class="title-center-align">Eventos</h1>
        <hr>
        <section class="card">
            <?php foreach($this->view->eventos as $evento) { ?>
                <?php if($evento['cancelado'] == 0) { ?>
                <form action="/acao_participante_evento?cGFydGljaXBhbnRl=<?= $usuarioID ?>" method="post" class="card-evento card-block">
                    <div class="card-img card-img-evento">
                        <?php if($evento['imgEvento'] != ''){ ?>
                            <img src="<?= $evento['imgEvento'] ?>" alt="evento">
                        <?php } else { ?>
                            <img src="./img/evento.png" alt="evento">
                        <?php } ?>
                    </div>
                    <div class="body-card body-card-evento">
                        <h1><?= $evento['titulo'] ?></h1>
                        <div>Responsável: <strong><?= $evento['nome'] ?></strong></div>
                        <div>Local: <strong><?= $evento['local'] ?></strong></div>
                        <div>Início: <strong><?= $evento['dataInicio'] ?></strong></div>
                        <div>Fim: <strong><?= $evento['dataFim'] ?></strong></div>
                        <p><?= $evento['descricao'] ?></p>

                        <div class="btn-card">
                            <?php if($evento['usuarioID'] == $_SESSION['id']) { ?>
                                <button type="submit" value="<?= $evento['id'] ?>" name="cancelarInscricaoEvento" class="btn-danger-full btn-block">Cancelar Inscrição</button>
                                <button type="submit" value="<?= $evento['id'] ?>" name="visualizarAtividades" class="btn-confirm-full btn-block">Ver Atividades</button>
                            <?php } else { ?>
                                <button type="submit" value="<?= $evento['id'] ?>" name="inscreverEvento" class="btn-register-full btn-block">Inscrever - me</button>
                            <?php } ?>
                        </div>
                    </div>
                </form>
                <?php } ?>
            <?php } ?>
        </section>
    </main>
</section>