<div class="bg-img">
    <img src="../img/event.png" alt="event">
</div>
<div class="card-login">
    <div  class="img-user">
        <img src="../img/user.png" alt="user">
    </div>
    <h1 class="title-login">Login</h1>
    <form action="/autenticar" method="post">
        <div class="input-grande">
            <label>E-mail: </label>
            <input type="text" name="login" class="input-login">
        </div>
        <div>
            <label class="label-login">Senha:</label>
            <input type="password" name="senha" class="input-login">
        </div>
        <div class="btn-align-center btn-space-top">
            <a href="/cadastro_usuario" class="btn-link btn-register btn-cadastro">Cadastre-se</a>
            <button type="submit" class="btn-confirm">Entrar</button>
        </div>

        <?php if($this->view->login == 'erro') { ?>
            <div class="msg-box msg-error">
                <small class="text-error">E-mail e/ou senha invalido(s)!</small>
            </div>
        <?php } ?>
        
    </form>
</div>