<div class="bg-img">
    <img src="../img/event.png" alt="event">
</div>
<div class="card-login">
    <div  class="img-user">
        <img src="../img/user.png" alt="user">
    </div>
    <h1 class="title-login">Login</h1>
    <form action="" method="post">
        <div class="input-grande">
            <label>E-mail: </label>
            <input type="text" class="input-login">
        </div>
        <div>
            <label class="label-login">Senha:</label>
            <input type="password" class="input-login">
        </div>
        <div class="btn-login">
            <a href="/cadastro_usuario" class="btn-link btn-register btn-cadastro">Cadastre-se</a>
            <button type="submit" class="btn-confirm btn-login">Entrar</button>
        </div>
    </form>
</div>