<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="author" content="BeatrizSantiago">
    
    <link rel="icon" type="imagem/png" href="./img/logosge.png" />

    <title>SGE</title>

    <link rel="stylesheet" href="./css/main.css">
    <link rel="stylesheet" href="./css/index.css">
    <link rel="stylesheet" href="./css/cadastro-usuario.css">
</head>
<body>
    <?= $this->content() ?>
</body>
</html>