<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="author" content="BeatrizSantiago">
    
    <link rel="icon" type="imagem/png" href="./img/logosge.png" />

    <title>SGE</title>

    <link rel="stylesheet" href="./css/main.css">

    <link rel="stylesheet" href="./css/components/menu.css">
    <link rel="stylesheet" href="./css/components/headers.css">

    <link rel="stylesheet" href="./css/utils/forms.css">
    <link rel="stylesheet" href="./css/utils/buttons.css">
    <link rel="stylesheet" href="./css/utils/mensagens.css">
    <link rel="stylesheet" href="./css/utils/listas.css">
    <link rel="stylesheet" href="./css/utils/cards.css">

    <link rel="stylesheet" href="./css/pages/index.css">
    <link rel="stylesheet" href="./css/pages/sucessoCadastro.css">
    <link rel="stylesheet" href="./css/pages/indexEvento.css">
    <link rel="stylesheet" href="./css/pages/indexAtividade.css">

    <script src="./js/main.js"></script>
</head>
<body>
    <?= $this->content() ?>
</body>
</html>