<?php

    require_once '../App/ValidaLoginResponsavelGeral.php';
    
    $eventoID = $_GET['idEvt'];
    if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') {
        $ResponsavelGeral = base64_encode($_SESSION['ResponsavelGeralID']);
    }

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <h1 class="apelido">Beatriz Santiago</h1>
        </div>
        <nav class="menu">
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">

    <div class="form-align">
        <?php foreach($this->view->dadosAtividades as $atividade) { ?>
            <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                <form action="/atualizar_atividade?idEvt=<?= $eventoID ?>&idAtv=<?= base64_encode($atividade['id']) ?>" method="post" class="form-register space-top">
            <?php } ?>

            <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                <form action="/atualizar_atividade?dXNlcklE=<?= $ResponsavelGeral ?>&idEvt=<?= $eventoID ?>&idAtv=<?= base64_encode($atividade['id']) ?>" method="post" class="form-register space-top">
            <?php } ?>

            <?php if($this->view->erroAtividade) { ?>
                <div class="msg-box msg-error">
                    <small class="text-error"><strong>Não foi possível alterar esta atividade!</strong> Modifique corretamente os campos necessários. </small>
                </div>
            <?php } ?>

            <div class="input-grande">
                <span>Tema</span>
                <input type="text" value="<?= $atividade['tema'] ?>" name="tema" maxlength="80" class="input-radius">
            </div>
            <div class="input-medio">
                <label>Tipo</label>
                <select name="tipo" class="input-radius">
                    <?php 
                        foreach($this->view->tipoAtividade as $tipoAtividade) { 
                            if($atividade['tipoID'] == $tipoAtividade['id']) {
                    ?>
                        <option value="<?= $tipoAtividade['id'] ?>" selected><?= $tipoAtividade['tipo'] ?></option>
                    <?php } else { ?>
                        <option value="<?= $tipoAtividade['id'] ?>"><?= $tipoAtividade['tipo'] ?></option>
                    <?php } } ?>
                </select>
            </div>
            <div class="input-extra-pequeno">
                <label>Vagas Mínimas</label>
                <input type="number" value="<?= $atividade['vagasMinimas'] ?>" name="vagasMinimas" class="input-radius">
            </div>
            <div class="input-extra-pequeno">
                <label>Vagas Máximas</label>
                <input type="number" value="<?= $atividade['vagasMaximas'] ?>" name="vagasMaximas" class="input-radius">
            </div>
            <div class="input-grande">
                <label>Responsável Pela Atividade</label>
                <select class="input-radius" name="responsavelAtividade">
                    <option value="">Selecione</option>
                    <?php 
                        foreach($this->view->dadosResponsavel as $dadosResponsavel) { 
                            if($atividade['respAtividadeID'] == $dadosResponsavel['id']) {
                    ?>
                        <option value="<?= $dadosResponsavel['id'] ?>" selected><?= $dadosResponsavel['nome'] ?></option>
                    <?php } else { ?>
                        <option value="<?= $dadosResponsavel['id'] ?>"><?= $dadosResponsavel['nome'] ?></option>
                    <?php } } ?>
                </select>
            </div>
            <div class="input-pequeno">
                <label>Data</label>
                <input type="date" value="<?= $atividade['data'] ?>" name="data" class="input-radius">
            </div>
            <div class="input-pequeno">
                <label>Hora</label>
                <input type="time" value="<?= $atividade['hora'] ?>" name="hora" class="input-radius">
            </div>
            <div class="input-pequeno">
                <label>Duração</label>
                <input type="time" value="<?= $atividade['duracao'] ?>" name="duracao" class="input-radius">
            </div>
            <div class="input-quase-grande">
                <label>Local</label>
                <input type="text" value="<?= $atividade['local'] ?>" name="local" maxlength="40" class="input-radius">
            </div>
            <div class="input-pequeno">
                <label>Pontos Pex</label>
                <input type="number" value="<?= $atividade['pontosPex'] ?>" name="pontosPex" class="input-radius">
            </div>
            <div class="input-grande">
                <label>Palestrante</label>
                <input type="text" value="<?= $atividade['palestrante'] ?>" name="palestrante" maxlength="65" class="input-radius">
            </div>
            <div class="input-grande">
                <label>Descrição</label>
                <textarea name="descricao" class="radius-textarea" rows="5" maxlength="180"><?= $atividade['descricao'] ?></textarea>
            </div>
            <div class="input-grande">
                <button type="submit" class="btn-register btn-right btn-space-top">Alterar Atividade</button>

                <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                    <a href="/index_atividade?idEvt=<?= $eventoID ?>" class="btn-link btn-right btn-space-top btn-confirm">Voltar</a>
                <?php } ?>
                
                <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                    <a href="/index_atividade?dXNlcklE=<?= $ResponsavelGeral ?>&idEvt=<?= $eventoID ?>" class="btn-link btn-right btn-space-top btn-confirm">Voltar</a>
                <?php } ?>
            </div>
        </form>
        <?php } ?>
    </div>

    </main>
</section>