<?php

    require_once '../App/ValidaLoginResponsavelAtividade.php';

    $eventoID = $_GET['idEvt'];
    $atividadeID = $_GET['idAtv'];
    if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') {
        $ResponsavelGeral = base64_encode($_SESSION['ResponsavelGeralID']);
    }

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <h1 class="apelido">Beatriz Santiago</h1>
        </div>
        <nav class="menu">
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">

        <section class="form-align">
            <?php if($_SESSION['tipoUsuario'] == 'Administrador' || $_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                <form action="/cadastrar?idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" method="post" class="form-register">
            <?php } ?>
            <?php if($_SESSION['tipoUsuario'] == 'ResponsavelAtividade') { ?>
                    <form action="/cadastrar?dXNlcklEQXR2=<?= $_GET['dXNlcklEQXR2'] ?>&idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" method="post" class="form-register">
            <?php } ?>
                <?php if($this->view->erroCadastro) { ?>
                    <div class="msg-box msg-error">
                        <small class="text-error"><strong>Erro ao tentar realizar o cadastro!</strong> Verifique se os campos foram preenchidos corretamente. </small>
                    </div>
                <?php } ?>
                <div class="input-grande">
                    <span>Nome</span>
                    <input type="text" name="nome" class="input-radius"/>
                </div>
                <div class="input-grande">
                    <label>Instituição de Ensino</label>
                    <input type="text" name="instituicao" class="input-radius"/>
                </div>
                <div class="input-medio">
                    <label>Curso</label>
                    <input type="text" name="curso" class="input-radius">
                </div>
                <div class="input-medio">
                    <label>Matrícula</label>
                    <input type="text" name="matricula" class="input-radius">
                </div>
                <div class="input-grande">
                    <label>E-mail</label>
                    <input type="text" name="login" class="input-radius">
                </div>
                <div class="input-medio">
                    <label>Senha</label>
                    <input type="text" name="senha" class="input-radius">
                </div>
                <div class="input-medio">
                    <label>Confirmar Senha</label>
                    <input type="text" name="confirmaSenha" class="input-radius">
                </div>
                <div class="input-grande">
                    <label>Foto de Perfil</label>
                    <input type="file" name="imgUser">
                </div>
                <div class="input-grande">
                    <button type="submit" class="btn-register btn-right">Cadastrar</button>
                    <?php if($_SESSION['tipoUsuario'] == 'Administrador' || $_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                        <a href="/listar_participante?idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" class="btn-link btn-confirm btn-right">Voltar</a>
                    <?php } ?>
                    <?php if($_SESSION['tipoUsuario'] == 'ResponsavelAtividade') { ?>
                        <a href="/listar_participante?dXNlcklEQXR2=<?= $_GET['dXNlcklEQXR2'] ?>&idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" class="btn-link btn-confirm btn-right">Voltar</a>
                    <?php } ?>
                </div>
            </form>
        </section>
    </main>
</section>