<?php

    require_once '../App/ValidaLoginResponsavelAtividade.php';

    $eventoID = $_GET['idEvt'];
    $atividadeID = $_GET['idAtv'];
    if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') {
        $ResponsavelGeral = base64_encode($_SESSION['ResponsavelGeralID']);
    }

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <?php if($_SESSION['tipoUsuario'] != 'Administrador' && $this->view->fotoPerfil[0]['imgUser'] != '') { ?>
                <img src="<?= $this->view->fotoPerfil[0]['imgUser'] ?>" alt="user" class="img-perfil">
            <?php } else { ?>
                <img src="./img/user.png" alt="user" class="img-perfil">
            <?php } ?>
            <div class="bemvindo">
                <h3>Bem-vindo(a),</h3>
                <h1 class="apelido"><?= ($_SESSION['apelido'] != '') ? $_SESSION['apelido'] : $_SESSION['login'] ?></h1>
            </div>
        </div>
        <nav class="menu">
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">

        <section class="form-align">
            <?php if($_SESSION['tipoUsuario'] == 'Administrador' || $_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                <form action="/inserirParticipante?idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" method="post" class="form-register">
            <?php } ?>
            <?php if($_SESSION['tipoUsuario'] == 'ResponsavelAtividade') { ?>
                    <form action="/inserirParticipante?dXNlcklEQXR2=<?= $_GET['dXNlcklEQXR2'] ?>&idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" method="post" class="form-register">
            <?php } ?>
                <?php if($this->view->erroCadastro) { ?>
                    <div class="msg-box msg-error">
                        <small class="text-error"><strong>Erro ao tentar realizar o cadastro!</strong> Verifique se os campos foram preenchidos corretamente. </small>
                    </div>
                <?php } ?>
                <div class="input-grande">
                    <span>Nome</span>
                    <input type="text" name="nome" class="input-radius" value="<?= $this->view->participante['nome'] ?>" autofocus/>
                    <?php if(isset($this->view->erroNome) && $this->view->erroNome != false) { ?>
                        <small class="text-error"><strong>Informe um nome válido!</strong></small>
                    <?php } ?>
                </div>
                <div class="input-grande">
                    <label>Instituição de Ensino</label>
                    <input type="text" name="instituicao" class="input-radius" value="<?= $this->view->participante['instituicao'] ?>"/>
                    <?php if(isset($this->view->erroInstituicao) && $this->view->erroInstituicao != false) { ?>
                        <small class="text-error"><strong>Informe uma Instituição de Ensino!</strong></small>
                    <?php } ?>
                </div>
                <div class="input-medio">
                    <label>Curso</label>
                    <input type="text" name="curso" class="input-radius" value="<?= $this->view->participante['curso'] ?>">
                    <?php if(isset($this->view->erroCurso) && $this->view->erroCurso != false) { ?>
                        <small class="text-error"><strong>Informe seu curso!</strong></small>
                    <?php } ?>
                </div>
                <div class="input-medio">
                    <label>Matrícula</label>
                    <input type="text" name="matricula" class="input-radius" value="<?= $this->view->participante['matricula'] ?>">
                    <?php if(isset($this->view->erroMatricula) && $this->view->erroMatricula != false) { ?>
                        <small class="text-error"><strong>Informe uma matrícula válida!</strong></small>
                    <?php } ?>
                </div>
                <div class="input-grande">
                    <label>E-mail</label>
                    <input type="email" name="login" class="input-radius" value="<?= $this->view->participante['login'] ?>">
                    <?php if(isset($this->view->erroEmail) && $this->view->erroEmail != false) { ?>
                        <small class="text-error"><strong>Informe o seu e-mail!</strong></small>
                    <?php } ?>
                    <?php if(isset($this->view->erroEmailRepetido) && $this->view->erroEmailRepetido != false) { ?>
                        <small class="text-error"><strong>Este e-mail já existe!</strong></small>
                    <?php } ?>
                </div>
                <div class="input-medio">
                    <label>Senha (no mínimo 6 caracteres)</label>
                    <input type="password" name="senha" class="input-radius" value="<?= $this->view->participante['senha'] ?>">
                    <?php if(isset($this->view->erroSenha) && $this->view->erroSenha != false) { ?>
                        <small class="text-error"><strong>Digite uma senha válida!</strong></small>
                    <?php } ?>
                </div>
                <div class="input-medio">
                    <label>Confirmar Senha</label>
                    <input type="password" name="confirmarSenha" class="input-radius">
                    <?php if(isset($this->view->erroConfirmarSenha) && $this->view->erroConfirmarSenha != false) { ?>
                        <small class="text-error"><strong>As senhas não coincidem!</strong></small>
                    <?php } ?>
                </div>
                <!-- <div class="input-grande">
                    <input type="hidden" name="MAX_FILE_SIZE" value="4194304" />
                    <label>Foto de Perfil</label>
                    <input type="file" name="imgUser">
                </div> -->
                <div class="input-grande btn-space-top">
                    <button type="submit" class="btn-register btn-right">Cadastrar</button>
                    <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                        <a href="/listar_participante?idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" class="btn-link btn-confirm btn-right">Voltar</a>
                    <?php } ?>
                    <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                        <a href="/listar_participante?dXNlcklE=<?= $_GET['dXNlcklE'] ?>&idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" class="btn-link btn-confirm btn-right">Voltar</a>
                    <?php } ?>
                    <?php if($_SESSION['tipoUsuario'] == 'ResponsavelAtividade') { ?>
                        <a href="/listar_participante?dXNlcklEQXR2=<?= $_GET['dXNlcklEQXR2'] ?>&idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" class="btn-link btn-confirm btn-right">Voltar</a>
                    <?php } ?>
                </div>
            </form>
        </section>
    </main>
</section>