<?php

    require_once '../App/ValidaLoginResponsavelGeral.php';
    
    $eventoID = $_GET['idEvt'];

    if($_SESSION['tipoUsuario'] == 'Administrador') {
        $url = '?idEvt=' . $eventoID;
    }

    if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') {
        $url = '?dXNlcklE=' . base64_encode($_SESSION['ResponsavelGeralID']) . '&idEvt=' . $eventoID;
    }

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <?php if($_SESSION['tipoUsuario'] != 'Administrador' && $this->view->fotoPerfil[0]['imgUser'] != '') { ?>
                <img src="<?= $this->view->fotoPerfil[0]['imgUser'] ?>" alt="user" class="img-perfil">
            <?php } else { ?>
                <img src="./img/user.png" alt="user" class="img-perfil">
            <?php } ?>
            <div class="bemvindo">
                <h3>Bem-vindo(a),</h3>
                <h1 class="apelido"><?= ($_SESSION['apelido'] != '') ? $_SESSION['apelido'] : $_SESSION['login'] ?></h1>
            </div>
        </div>
        <nav class="menu">
            <a href="/index_evento<?= $_SESSION['tipoUsuario'] == 'ResponsavelGeral' ? $url : '' ?>"><img src="./img/icons/eventos.png">Eventos</a>
            <a href="/index_atividade<?= $url ?>"><img src="./img/icons/atividade.png">Atividades</a>
            <a href="/responsavel_atividade<?= $url ?>"><img src="./img/icons/resp-atv.png">Responsável por Atividade</a>
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">

    <div class="form-align">
        <form enctype="multipart/form-data" action="/cadastrar_atividade<?= $url ?>" method="post" class="form-register space-top">
            <?php if($this->view->erroAtividade) { ?>
                <div class="msg-box msg-error">
                    <small class="text-error"><strong>Erro ao tentar criar a atividade!</strong> Verifique se os campos foram preenchidos corretamente. </small>
                </div>
            <?php } ?>

            <div class="input-grande">
                <span>Tema</span>
                <input type="text" name="tema" maxlength="80" class="input-radius" value="<?= $this->view->atividade['tema'] ?>" autofocus>
                <?php if(isset($this->view->erroTema) && $this->view->erroTema != false) { ?>
                    <small class="text-error"><strong>Informe um tema válido!</strong></small>
                <?php } ?>
            </div>

            <div class="input-medio">
                <label>Tipo</label>
                <select name="tipo" class="input-radius">
                    <option value="">Selecione</option>
                    <?php foreach($this->view->tipo_atividade as $tipoAtividade) { 
                        if($this->view->atividade['tipo'] == $tipoAtividade['id']) { ?>
                            <option value="<?= $tipoAtividade['id'] ?>" selected><?= $tipoAtividade['tipo'] ?></option>
                        <?php } else { ?>
                            <option value="<?= $tipoAtividade['id'] ?>"><?= $tipoAtividade['tipo'] ?></option>
                    <?php } } ?>
                </select>

                <?php if(isset($this->view->erroTipo) && $this->view->erroTipo != false) { ?>
                    <small class="text-error"><strong>Informe o tipo da atividade!</strong></small>
                <?php } ?>
            </div>

            <div class="input-extra-pequeno">
                <label>Vagas Mínimas</label>
                <input type="number" name="vagasMinimas" class="input-radius" value="<?= $this->view->atividade['vagasMinimas'] ?>">
                <?php if(isset($this->view->erroVagasMinimas) && $this->view->erroVagasMinimas != false) { ?>
                    <small class="text-error"><strong>Informe uma quantidade válida de vagas!</strong></small>
                <?php } ?>
            </div>
            <div class="input-extra-pequeno">
                <label>Vagas Máximas</label>
                <input type="number" name="vagasMaximas" class="input-radius" value="<?= $this->view->atividade['vagasMaximas'] ?>">
                <?php if(isset($this->view->erroVagasMaximas) && $this->view->erroVagasMaximas != false) { ?>
                    <small class="text-error"><strong>Informe uma quantidade válida de vagas!</strong></small>
                <?php } ?>
            </div>

            <div class="input-grande">
                <label>Responsável da Atividade</label>
                <select class="input-radius" name="responsavelAtividade">
                    <option value="">Selecione</option>
                    <?php foreach($this->view->responsavel_atividade as $responsavel_atividade) { 
                        if($this->view->atividade['responsavelAtividade'] == $responsavel_atividade['id']) { ?>
                            <option value="<?= $responsavel_atividade['id'] ?>" selected><?= $responsavel_atividade['nome'] ?></option>
                        <?php } else { ?>
                            <option value="<?= $responsavel_atividade['id'] ?>"><?= $responsavel_atividade['nome'] ?></option>
                    <?php } } ?>
                </select>

                <?php if(isset($this->view->erroResponsavelAtividade) && $this->view->erroResponsavelAtividade != false) { ?>
                    <small class="text-error"><strong>Informe um Responsável da Atividade!</strong></small>
                <?php } ?>
            </div>

            <div class="input-pequeno">
                <label>Data</label>
                <input type="date" name="data" class="input-radius" value="<?= $this->view->atividade['data'] ?>">
                <?php if(isset($this->view->erroData) && $this->view->erroData != false) { ?>
                    <small class="text-error"><strong>Informe uma data válida!</strong></small>
                <?php } ?>
                <?php if((isset($this->view->erroDataMenor) && $this->view->erroDataMenor != false) || (isset($this->view->erroDataMaior) && $this->view->erroDataMaior != false)) { ?>
                    <small class="text-error"><strong>A data deve estar entre início e o final do evento!</strong></small>
                <?php } ?>
            </div>
            <div class="input-pequeno">
                <label>Hora</label>
                <input type="time" name="hora" class="input-radius" value="<?= $this->view->atividade['hora'] ?>">
                <?php if(isset($this->view->erroHora) && $this->view->erroHora != false) { ?>
                    <small class="text-error"><strong>Informe um horário válido!</strong></small>
                <?php } ?>
            </div>
            <div class="input-pequeno">
                <label>Duração</label>
                <input type="time" name="duracao" class="input-radius" value="<?= $this->view->atividade['duracao'] ?>">
                <?php if(isset($this->view->erroDuracao) && $this->view->erroDuracao != false) { ?>
                    <small class="text-error"><strong>Informe uma duração válida!</strong></small>
                <?php } ?>
            </div>
            <div class="input-quase-grande">
                <label>Local</label>
                <input type="text" name="local" maxlength="40" class="input-radius" value="<?= $this->view->atividade['local'] ?>">
                <?php if(isset($this->view->erroLocal) && $this->view->erroLocal != false) { ?>
                    <small class="text-error"><strong>Informe um local!</strong></small>
                <?php } ?>
            </div>
            <div class="input-pequeno">
                <label>Pontos Pex</label>
                <input type="number" name="pontosPex" class="input-radius" value="<?= $this->view->atividade['pontosPex'] ?>">
                <?php if(isset($this->view->erroPontosPex) && $this->view->erroPontosPex != false) { ?>
                    <small class="text-error"><strong>Informe a quantidade de PEX!</strong></small>
                <?php } ?>
            </div>
            <div class="input-medio">
                <label>Palestrante</label>
                <input type="text" name="palestrante" maxlength="65" class="input-radius" value="<?= $this->view->atividade['palestrante'] ?>">
                <?php if(isset($this->view->erroPalestrante) && $this->view->erroPalestrante != false) { ?>
                    <small class="text-error"><strong>Informe um palestrante!</strong></small>
                <?php } ?>
            </div>
            <div class="input-medio">
                <input type="hidden" name="MAX_FILE_SIZE" value="835584" />
                <label>Foto do Palestrante</label>
                <input type="file" name="imgPalestrante" accept="image/*">
                <?php if(isset($this->view->erroImage) && $this->view->erroImage != false) { ?>
                    <small class="text-error"><strong>A imagem excede o limite de tamanho!</strong></small>
                <?php } ?>
            </div>
            <div class="input-grande">
                <label>Descrição</label>
                <textarea name="descricao" class="radius-textarea" rows="5" maxlength="180" value="<?= $this->view->atividade['descricao'] ?>"></textarea>
            </div>
            <div class="input-grande">
                <button type="submit" class="btn-register btn-right btn-space-top">Adicionar Atividade</button>
                <a href="/index_atividade<?= $url ?>" class="btn-link btn-right btn-space-top btn-confirm">Voltar</a>
            </div>
        </form>
    </div>

    </main>
</section>