<?php

    require_once '../App/ValidaLoginResponsavelGeral.php';

    $eventoID = $_GET['idEvt'];
    if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') {
        $ResponsavelGeral = base64_encode($_SESSION['ResponsavelGeralID']);
    }

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <h1 class="apelido">Beatriz Santiago</h1>
        </div>
        <nav class="menu">
            <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                <a href="/index_evento"><img src="./img/icons/eventos.png">Eventos</a>
                <a href="/criar_atividade?idEvt=<?= $eventoID ?>"><img src="./img/icons/criar-atv.png">Criar Atividade</a>
                <a href="/responsavel_atividade?idEvt=<?= $eventoID ?>"><img src="./img/icons/resp-atv.png">Responsável por Atividade</a>
            <?php } ?>

            <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                <a href="/index_evento?dXNlcklE=<?= $ResponsavelGeral ?>"><img src="./img/icons/eventos.png">Eventos</a>
                <a href="/criar_atividade?dXNlcklE=<?= $ResponsavelGeral ?>&idEvt=<?= $eventoID ?>"><img src="./img/icons/criar-atv.png">Criar Atividade</a>
                <a href="/responsavel_atividade?dXNlcklE=<?= $ResponsavelGeral ?>&idEvt=<?= $eventoID ?>"><img src="./img/icons/resp-atv.png">Responsável por Atividade</a>
            <?php } ?>
            
            <a href="#"><img src="./img/icons/criar-evento.png">Cronograma</a>
            <a href="/relatorio_evento?idEvt=<?= $eventoID ?>" target="_blank"><img src="./img/icons/relatorio.png">Gerar Relatório</a>
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">
        <h1 class="title-center-align">Atividades de <?= $this->view->titulo[0]['titulo'] ?></h1>
        <hr>
        <?php if($this->view->atividades == []) { ?>
            <div class="mensagem-aviso">
                <div class="msg-box-medium msg-info">
                    <small class="text-info">Ainda <strong>não existem atividades</strong> para este evento!</small>
                </div>
            </div>
        <?php } ?>
        <section class="card">
            <?php foreach($this->view->atividades as $atividade) { ?>
                <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                    <form action="/acao_atividade?idEvt=<?= $eventoID ?>&idAtv=<?= base64_encode($atividade['id']) ?>" method="post" class="card-atividade card-block">
                <?php } ?>
                <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                        <form action="/acao_atividade?dXNlcklE=<?= $ResponsavelGeral ?>&idEvt=<?= $eventoID ?>&idAtv=<?= base64_encode($atividade['id']) ?>" method="post" class="card-atividade card-block">
                <?php } ?>

                    <div class="body-card body-card-atividade">
                        <h1><?= $atividade['tipo'] ?></h1>
                        <div class="div-grande">Tema: <strong><?= $atividade['tema'] ?></strong></div>
                        <div class="div-grande">Palestrante <strong><?= $atividade['palestrante'] ?></strong></div>
                        <div class="div-grande">Responsável: <strong><?= $atividade['nome'] ?></strong></div>
                        <div class="div-grande">Local: <strong><?= $atividade['local'] ?></strong></div>
                        
                        <div class="div-grande">
                            <div class="div-media">Data: <strong><?= $atividade['data'] ?></strong></div>
                            <div class="div-media">Hora: <strong><?= $atividade['hora'] ?>h</strong></div>
                        </div>
                        
                        <div class="div-grande">
                            <div class="div-media">Duração: <strong><?= $atividade['duracao'] ?>h</strong></div>
                            <div class="div-media">Pontos Pex: <strong><?= $atividade['pontosPex'] ?></strong></div>
                        </div>

                        <div class="div-grande">
                            <div class="div-media">Total de Vagas: <strong><?= $atividade['vagasMaximas'] ?></strong></div>
                            <div class="div-media">Vagas Mínimas: <strong><?= $atividade['vagasMinimas'] ?></strong></div>
                        </div>

                        <div class="div-grande">Inscritos: <strong>00</strong></div>

                        <?php if($atividade['descricao'] != '') { ?>
                            <p><?= $atividade['descricao'] ?></p>
                        <?php } else { ?>
                            <br/>
                        <?php } ?>

                        <div class="btn-card btn-card-atividade">
                            <button type="submit" name="excluir" value="<?= $atividade['id'] ?>" class="btn-evil-full"><img class="img-button" src="./img/icons/delete.png" /></button>
                            <?php if($atividade['cancelada'] == false) { ?>
                                <button type="submit" name="cancelar" value="<?= $atividade['id'] ?>" class="btn-danger-full"><img class="img-button" src="./img/icons/cancel.png" /></button>
                            <?php } else { ?>
                                <button type="submit" name="ativar" value="<?= $atividade['id'] ?>" class="btn-register-full">Ativar</button>
                            <?php } ?>
                            <button type="submit" name="alterar" value="<?= $atividade['id'] ?>" class="btn-warning-full"><img class="img-button" src="./img/icons/edit.png" /></button>
                            <button type="submit" name="participantes" value="<?= $atividade['id'] ?>" class="btn-confirm-full"><img class="img-button" src="./img/icons/participante.png" /></button>
                        </div>
                    </div>

                </form>
            <?php } ?>
        </section>
    </main>
</section>