<?php

    require_once '../App/ValidaLoginResponsavelAtividade.php';

    $eventoID = $_GET['idEvt'];
    $atividadeID = $_GET['idAtv'];
    if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') {
        $ResponsavelGeral = base64_encode($_SESSION['ResponsavelGeralID']);
    }

    if($_SESSION['tipoUsuario'] == 'ResponsavelAtividade') {
        $ResponsavelAtividade = base64_encode($_SESSION['ResponsavelAtividadeID']);
    }

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <h1 class="apelido">Beatriz Santiago</h1>
        </div>
        <nav class="menu">

            <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                <a href="/index_evento"><img src="./img/icons/eventos.png">Eventos</a>
                <a href="/index_atividade?idEvt=<?= $eventoID ?>"><img src="./img/icons/atividade.png">Atividades</a>
            <?php } ?>
                
            <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                <a href="/index_evento?dXNlcklE=<?= $ResponsavelGeral ?>"><img src="./img/icons/eventos.png">Eventos</a>
                <a href="/index_atividade?dXNlcklE=<?= $ResponsavelGeral ?>&idEvt=<?= $eventoID ?>"><img src="./img/icons/atividade.png">Atividades</a>
            <?php } ?>

            <?php if($_SESSION['tipoUsuario'] == 'ResponsavelAtividade') { ?>
                <a href="/gerenciar_atividades?dXNlcklEQXR2=<?= $ResponsavelAtividade ?>"><img src="./img/icons/atividade.png">Gerenciar Atividades</a>
            <?php } ?>

            <a><img src="./img/icons/relatorio.png">Gerar Relatório</a>
            <a href="/lista_presenca?idAtv=<?= $atividadeID ?>" target="_blank"><img src="./img/icons/relatorio.png">Lista de Presença</a>
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">

        <section class="form-align">
            <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                <form action="/adicionar_participante?idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" method="post" class="form-register">
            <?php } ?>

            <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                <form action="/adicionar_participante?dXNlcklE=<?= $ResponsavelGeral ?>&idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" method="post" class="form-register">
            <?php } ?>

            <?php if($_SESSION['tipoUsuario'] == 'ResponsavelAtividade') { ?>
                <form action="/adicionar_participante?dXNlcklEQXR2=<?= $ResponsavelAtividade ?>&idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" method="post" class="form-register">
            <?php } ?>
                <h1 class="title-center-align">Adicionar Participante</h1>
                <div class="input-grande">
                    <label>E-mail do Usuário</label>
                    <input type="email" name="login" class="input-radius">
                </div>
                <div class="input-grande btn-align-center btn-space-top">
                    <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                        <a href="/cadastrar_participante?idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" class="btn-link btn-confirm">Cadastrar Participante</a>
                    <?php } ?>
                    <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                            <a href="/cadastrar_participante?dXNlcklE=<?= $ResponsavelGeral ?>&idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" class="btn-link btn-confirm">Cadastrar Participante</a>
                    <?php } ?>
                    <?php if($_SESSION['tipoUsuario'] == 'ResponsavelAtividade') { ?>
                            <a href="/cadastrar_participante?dXNlcklEQXR2=<?= $ResponsavelAtividade ?>&idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" class="btn-link btn-confirm">Cadastrar Participante</a>
                    <?php } ?>
                    
                    <button type="submit" class="btn-register">Adicionar</button>
                </div>
            </form>
        </section>

        <h1 class="title-center-align">Participantes de <?= $this->view->tituloAtividade[0]['tema'] ?></h1>
        <hr>

        <section class="lista-container">
            <div class="lista-header">
                <div class="item-minimo">Nome</div>
                <div class="item-minimo">E-mail</div>
                <div class="item-minimo">Curso</div>
                <div class="item-minimo">Matrícula</div>
                <div class="item-button"></div>
            </div>
            <div class="lista">
                <?php foreach($this->view->inscritos as $inscritos) {?>
                    <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                        <form action="/acao_lista_participante?idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" method="post" class="item-lista">
                    <?php } ?>

                    <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                        <form action="/acao_lista_participante?dXNlcklE=<?= $ResponsavelGeral ?>&idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" method="post" class="item-lista">
                    <?php } ?>

                    <?php if($_SESSION['tipoUsuario'] == 'ResponsavelAtividade') { ?>
                        <form action="/acao_lista_participante?dXNlcklEQXR2=<?= $ResponsavelAtividade ?>&idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" method="post" class="item-lista">
                    <?php } ?>
                        <div class="item-minimo"><?= $inscritos['nome'] ?></div>
                        <div class="item-minimo"><?= $inscritos['login'] ?></div>
                        <div class="item-minimo"><?= $inscritos['curso'] ?></div>
                        <div class="item-minimo"><?= $inscritos['matricula'] ?></div>
                        <?php if($inscritos['presente'] == 0) { ?>
                            <button type="submit" value="<?= $inscritos['login'] ?>" name="remover" class="btn-danger-full"><img class="img-button" src="./img/icons/cancel.png" /></button>
                            <button type="submit" value="<?= $inscritos['login'] ?>" name="confirmar" class="btn-register-full"><img class="img-button" src="./img/icons/ativar.png" /></button>
                        <?php } else { ?>
                            <div class="item-button"></div>
                        <?php } ?>
                    </form>
                <?php } ?>
            </div>
        </section>
    </main>
</section>