<?php

    require_once '../App/ValidaLoginAdministrador.php';

    $eventoID = $_GET['idEvt'];
    $atividadeID = $_GET['idAtv'];

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <h1 class="apelido">Beatriz Santiago</h1>
        </div>
        <nav class="menu">
            <a href="/index_evento"><img src="./img/icons/eventos.png">Meus Eventos</a>
            <a href="/index_atividade?idEvt=<?= $eventoID ?>"><img src="./img/icons/atividade.png">Atividades</a>
            <a><img src="./img/icons/relatorio.png">Gerar Relatório</a>
            <a href="/lista_presenca?idAtv=<?= $atividadeID ?>" target="_blank"><img src="./img/icons/relatorio.png">Lista de Presença</a>
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">

        <section class="form-align">
            <form action="/adicionar_participante?idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" method="post" class="form-register">
                <h1 class="title-center-align">Adicionar Participante</h1>
                <div class="input-grande">
                    <label>E-mail do Usuário</label>
                    <input type="text" name="login" class="input-radius">
                </div>
                <div class="input-grande btn-align-center btn-space-top">
                    <button type="submit" class="btn-register">Adicionar</button>
                </div>
            </form>
        </section>

        <h1 class="title-center-align">Participantes de <?= $this->view->tituloAtividade[0]['tema'] ?></h1>
        <hr>

        <section class="lista-container">
            <div class="lista-header">
                <div class="item-pequeno">Nome</div>
                <div class="item-pequeno">E-mail</div>
                <div class="item-pequeno">Curso</div>
                <div class="item-button"></div>
            </div>
            <div class="lista">
                <?php foreach($this->view->inscritos as $inscritos) {?>
                    <form action="/remover_participante?idEvt=<?= $eventoID ?>&idAtv=<?= $atividadeID ?>" method="post" class="item-lista">
                        <div class="item-pequeno"><?= $inscritos['nome'] ?></div>
                        <div class="item-pequeno"><?= $inscritos['login'] ?></div>
                        <div class="item-pequeno"><?= $inscritos['curso'] ?></div>
                        <div class="item-button">
                            <button type="submit" value="<?= $inscritos['login'] ?>" name="remover" class="btn-danger-full">Remover</button>
                        </div>
                    </form>
                <?php } ?>
            </div>
        </section>
    </main>
</section>