<aside class="menu-lateral">
    <div class="form-align">
        <h1>Logo SGE</h1>
        <img src="./img/user.png" alt="user" class="img-perfil">
        <h1 class="apelido">Beatriz Santiago</h1>
    </div>
    <nav class="menu">
        <a href="/index_evento"><img src="./img/icons/eventos.png">Meus Eventos</a>
        <a href="/index_atividade"><img src="./img/icons/atividade.png">Atividade</a>
        <a href="/criar_atividade"><img src="./img/icons/criar-atv.png">Criar Atividade</a>
        <a href="/responsavel_atividade"><img src="./img/icons/resp-atv.png">Responsável por Atividade</a>
        <a><img src="./img/icons/relatorio.png">Gerar Relatório</a>
        <a href="/sair" class="sair">Sair</a>
    </nav>
</aside>