<aside class="menu-lateral">
    <div class="form-align">
        <h1>Logo SGE</h1>
        <img src="./img/user.png" alt="user" class="img-perfil">
        <h1 class="apelido">Beatriz Santiago</h1>
    </div>
    <nav class="menu">
        <a href="/index_evento">Meus Eventos</a>
        <a href="/index_atividade">Atividade</a>
        <a href="/criar_atividade">Criar Atividade</a>
        <a href="/responsavel_atividade">Responsável Atividade</a>
        <a>Gerar Relatório</a>
        <a href="/sair">Sair</a>
    </nav>
</aside>