<?php

    require_once '../App/ValidaLoginResponsavelGeral.php';

    $eventoID = $_GET['idEvt'];
    if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') {
        $ResponsavelGeral = base64_encode($_SESSION['ResponsavelGeralID']);
    }

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <?php if($_SESSION['tipoUsuario'] != 'Administrador' && $this->view->fotoPerfil[0]['imgUser'] != '') { ?>
                <img src="<?= $this->view->fotoPerfil[0]['imgUser'] ?>" alt="user" class="img-perfil">
            <?php } else { ?>
                <img src="./img/user.png" alt="user" class="img-perfil">
            <?php } ?>
            <div class="bemvindo">
                <h3>Bem-vindo(a),</h3>
                <h1 class="apelido"><?= ($_SESSION['apelido'] != '') ? $_SESSION['apelido'] : $_SESSION['login'] ?></h1>
            </div>
        </div>
        <nav class="menu">
            <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                <a href="/index_evento"><img src="./img/icons/eventos.png">Eventos</a>
                <a href="/index_atividade?idEvt=<?= $eventoID ?>"><img src="./img/icons/atividade.png">Atividade</a>
                <a href="/criar_atividade?idEvt=<?= $eventoID ?>"><img src="./img/icons/criar-atv.png">Criar Atividade</a>
            <?php } ?>

            <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                <a href="/index_evento?dXNlcklE=<?= $ResponsavelGeral ?>"><img src="./img/icons/eventos.png">Eventos</a>
                <a href="/index_atividade?dXNlcklE=<?= $ResponsavelGeral ?>&idEvt=<?= $eventoID ?>"><img src="./img/icons/atividade.png">Atividade</a>
                <a href="/criar_atividade?dXNlcklE=<?= $ResponsavelGeral ?>&idEvt=<?= $eventoID ?>"><img src="./img/icons/criar-atv.png">Criar Atividade</a>
            <?php } ?>

            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">

    <section class="form-align">
        <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
            <form action="/cadastrar_responsavel_atividade?idEvt=<?= $eventoID ?>" method="post" class="form-register">
        <?php } ?>
        <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
            <form action="/cadastrar_responsavel_atividade?dXNlcklE=<?= $ResponsavelGeral ?>&idEvt=<?= $eventoID ?>" method="post" class="form-register">
        <?php } ?>
            <h1 class="title-center-align">Cadastrar Responsável de Atividade</h1>
            <div class="input-grande">
                <label>E-mail do Usuário</label>
                <input type="email" name="login" class="input-radius" value="<?= $this->view->responsavelAtividade['login'] ?>">
                <?php if(isset($this->view->erroEmailCadastrado) && $this->view->erroEmailCadastrado != false) { ?>
                    <small class="text-error"><strong> Este Responsável de Atividade já existe!</strong></small>
                <?php } ?>
                <?php if(isset($this->view->erroEmail) && $this->view->erroEmail != false) { ?>
                    <small class="text-error"><strong> Informe um e-mail!</strong></small>
                <?php } ?>
            </div>
            <div class="input-grande btn-align-center btn-space-top">
                <button type="submit" class="btn-register">Adicionar Responsável</button>
            </div>
        </form>
    </section>

    <h1 class="title-center">Responsável Atividade</h1>
    <hr>

    <section class="lista-container">
        <div class="lista-header">
            <div class="item-pequeno">Nome</div>
            <div class="item-pequeno">E-mail</div>
            <div class="item-pequeno">Matrícula</div>
            <div class="item-button"></div>
        </div>

        <div class="lista">
            <?php foreach($this->view->responsavel_atividade as $item) {?>
                <?php if($_SESSION['tipoUsuario'] == 'Administrador') { ?>
                    <form action="/remover_responsavel_atividade?idEvt=<?= $eventoID ?>" method="post" class="item-lista">
                <?php } ?>
                <?php if($_SESSION['tipoUsuario'] == 'ResponsavelGeral') { ?>
                    <form action="/remover_responsavel_atividade?dXNlcklE=<?= $ResponsavelGeral ?>&idEvt=<?= $eventoID ?>" method="post" class="item-lista">
                <?php } ?>
                    <div class="item-pequeno"><?= $item['nome'] ?></div>
                    <div class="item-pequeno"><?= $item['login'] ?></div>
                    <div class="item-pequeno"><?= $item['matricula'] ?></div>
                    <div class="item-button">
                        <button type="submit" value="<?= $item['id'] ?>" name="remover" class="btn-danger-full">Remover</button>
                    </div>
                </form>
            <?php } ?>
        </div>
    </section>

    </main>
</section>