<?php

    require_once '../App/ValidaLogin.php';

?>

<section class="grid-base">
    <aside class="menu-topo">
        <div class="form-menu">
            <img src="./img/user.png" alt="user" class="img-perfil">
            <h1 class="apelido">Beatriz Santiago</h1>
        </div>
        <nav class="menu">
            <a href="/index_evento"><img src="./img/icons/eventos.png">Meus Eventos</a>
            <a href="/index_atividade"><img src="./img/icons/atividade.png">Atividade</a>
            <a href="/criar_atividade"><img src="./img/icons/criar-atv.png">Criar Atividade</a>
            <a href="/responsavel_atividade"><img src="./img/icons/resp-atv.png">Responsável por Atividade</a>
            <a><img src="./img/icons/relatorio.png">Gerar Relatório</a>
            <div class="div-sair">
                <a href="/sair" class="sair">Sair</a>
            </div>
        </nav>
    </aside>

    <main class="content">

    <div class="form-align">
        <form action="/cadastrar_responsavel_atividade" method="post" class="form-register space-top">
            <h1 class="title-center-align">Cadastrar Responsável de Atividade</h1>
            <div class="input-grande">
                <label>E-mail do Usuário</label>
                <input type="text" name="login" class="input-radius">
            </div>
            <div class="input-grande btn-align-center btn-space-top">
                <button type="submit" class="btn-register">Adicionar Responsável</button>
            </div>
        </form>
        <div class="lista space-top">
            <h1 class="title-center">Responsável Atividade</h1>
            <hr>
            <?php foreach($this->view->responsavel_atividade as $item) {?>
                <form action="/remover_responsavel_atividade" method="post" class="item-lista">
                    <div class="item-medio"><?= $item['nome'] ?></div>
                    <div class="item-medio"><?= $item['login'] ?></div>
                    <div class="item-button">
                        <button type="submit" value="<?= $item['id'] ?>" name="remover" class="btn-danger-full">Remover</button>
                    </div>
                </form>
            <?php } ?>
        </div>
    </div>

    </main>
</section>